apiVersion: v1
kind: Service
metadata:
  name: {{ include "sliding-puzzle.fullname" . }}-nginx
  labels:
    app: {{ include "sliding-puzzle.name" . }}-nginx
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.nginx.service.httpPort }}
      targetPort: {{ .Values.nginx.service.httpPort }}
    - name: https
      port: {{ .Values.nginx.service.httpsPort }}
      targetPort: {{ .Values.nginx.service.httpsPort }}
  selector:
    app: {{ include "sliding-puzzle.name" . }}-nginx
