apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sliding-puzzle.fullname" . }}-nginx
  labels:
    app: {{ include "sliding-puzzle.name" . }}-nginx
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "sliding-puzzle.name" . }}-nginx
  template:
    metadata:
      labels:
        app: {{ include "sliding-puzzle.name" . }}-nginx
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.nginx.service.httpPort }}
        - name: https
          containerPort: {{ .Values.nginx.service.httpsPort }}
