apiVersion: v1
kind: Service
metadata:
  name: {{ include "sliding-puzzle.fullname" . }}-frontend
  labels:
    app: {{ include "sliding-puzzle.name" . }}-frontend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
  selector:
    app: {{ include "sliding-puzzle.name" . }}-frontend
