apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-sa
  namespace: default
  labels:
    app.kubernetes.io/name: monitoring-sa
    app.kubernetes.io/managed-by: Helm
    # Add any other labels you want

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitoring-sa-role
  labels:
    app.kubernetes.io/name: monitoring-sa
    app.kubernetes.io/managed-by: Helm
rules:
  # Core API resources
  - apiGroups: [""]
    resources: ["pods", "nodes", "services"]
    verbs: ["get", "list", "watch"]

  # Metrics API resources (from metrics.k8s.io)
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch"]

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-sa-binding
  labels:
    app.kubernetes.io/name: monitoring-sa
    app.kubernetes.io/managed-by: Helm
subjects:
  - kind: ServiceAccount
    name: monitoring-sa
    namespace: default # <-- Must match ServiceAccount namespace
roleRef:
  kind: ClusterRole
  name: monitoring-sa-role
  apiGroup: rbac.authorization.k8s.io
